//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Usuario
    {
        public int Id { get; set; }
        public string Cpf { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Nascimento { get; set; }
        public string Nome { get; set; }
        public string Rg { get; set; }
        public string Senha { get; set; }
        public string Sexo { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
    
        public virtual Endereco Endereco { get; set; }
    }
}
