//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente : Usuario
    {
        public Cliente()
        {
            this.Venda = new HashSet<Venda>();
        }
    
    
        public virtual ICollection<Venda> Venda { get; set; }
    }
}
