//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loja
    {
        public Loja()
        {
            this.Fornecedor = new HashSet<Fornecedor>();
            this.Caixa = new HashSet<Caixa>();
            this.Venda = new HashSet<Venda>();
            this.Funcionario = new HashSet<Funcionario>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Fornecedor> Fornecedor { get; set; }
        public virtual ICollection<Caixa> Caixa { get; set; }
        public virtual Estoque Estoque { get; set; }
        public virtual ICollection<Venda> Venda { get; set; }
        public virtual Endereco Endereco { get; set; }
        public virtual ICollection<Funcionario> Funcionario { get; set; }
    }
}
