//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermissoesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermissoesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelLib.PermissoesResource", typeof(PermissoesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Compras de outros vendedores.
        /// </summary>
        public static string EditarCompras {
            get {
                return ResourceManager.GetString("EditarCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançar Entradas e Saídas de Estoque.
        /// </summary>
        public static string GerenciarEstoque {
            get {
                return ResourceManager.GetString("GerenciarEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar e Alterar Fornecedores.
        /// </summary>
        public static string GerenciarFornecedores {
            get {
                return ResourceManager.GetString("GerenciarFornecedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar novos Funcionários.
        /// </summary>
        public static string GerenciarFuncionarios {
            get {
                return ResourceManager.GetString("GerenciarFuncionarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar e Alterar Produtos.
        /// </summary>
        public static string GerenciarProdutos {
            get {
                return ResourceManager.GetString("GerenciarProdutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançar Compras.
        /// </summary>
        public static string LancarCompras {
            get {
                return ResourceManager.GetString("LancarCompras", resourceCulture);
            }
        }
    }
}
