//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.ProdutoVendaItem = new HashSet<ProdutoVendaItem>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public double PrecoCusto { get; set; }
        public double PrecoVista { get; set; }
        public Nullable<double> PrecoPrazo { get; set; }
        public Nullable<double> Quantidade { get; set; }
        public Nullable<bool> DisponivelLojaVirtual { get; set; }
        public string Descricao { get; set; }
        public string UnidadeMedida { get; set; }
        public Nullable<byte> Imagem { get; set; }
        public int Codigo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual ICollection<ProdutoVendaItem> ProdutoVendaItem { get; set; }
    }
}
